### ISSUE TITLE
The choose_layers_by_changes function is not implemented in the utils.py file. 

### ISSUE THREAD

**Issue by gray311** [mit-han-lab/offsite-tuning#3]
There should be a problem with the import choose_layers_by_changes function in run_clm.py.
![figure 2023-02-27 141719](https://user-images.githubusercontent.com/64787301/221489617-1877cb77-112d-4374-8b7e-1f9ba782498e.png)

**Comment by Guangxuan-Xiao** [comment]
Thank you for spotting this bug! We did not use this function in the final version.

**Comment by Guangxuan-Xiao** [comment]
Fixed now.

**Comment by gray311** [comment]
I have one more question. It is that the attribute model.module is not defined in your code, so why is it called in run_clm.py?
![屏幕截图 2023-02-28 134443](https://user-images.githubusercontent.com/64787301/221766814-14a0d18d-923f-410a-b738-e2144066ed13.png)
