### ISSUE TITLE
Suggestion to upload large files to cloud drive

### ISSUE THREAD

**Issue by iseesaw** [mit-han-lab/offsite-tuning#7]
Hi there,

I noticed that some of the files in this repository are quite large and it's causing issues with downloading them. I wanted to suggest that you consider uploading these files to a cloud drive like Google Drive or Dropbox so that users can download them more easily.

Thanks!

```
Downloading emulators/CLIP-ViT-H-14-laion2B-s32B-b79K/16_4_4/all_results.json (220 B)
Error downloading object: emulators/CLIP-ViT-H-14-laion2B-s32B-b79K/16_4_4/all_results.json (7b025d0): Smudge error: Error downloading emulators/CLIP-ViT-H-14-laion2B-s32B-b79K/16_4_4/all_results.json (7b025d0ce3e61c7118f81f02585ccfe75b281fffcde0847a9ef3680461daaaf3): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /root/kyzhang/studio/offsite-tuning/.git/lfs/logs/20230329T110502.481473204.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: emulators/CLIP-ViT-H-14-laion2B-s32B-b79K/16_4_4/all_results.json: smudge filter lfs failed
```

**Comment by jyhong836** [comment]
Try some workaround for downloading LFS files: https://stackoverflow.com/questions/62905325/this-repository-is-over-its-data-quota-account-responsible-for-lfs-bandwidth-sh

**Comment by krishnakanthnakka** [comment]
Dear all,

If anyone able to download the large files in the emulators folder, please share the details. I was not able to to download the files with the methods mentioned in the above stack-overflow link.

Thanks

**Comment by Guangxuan-Xiao** [comment]
We uploaded the emulators and models we used in our paper to [Huggingface](https://huggingface.co/mit-han-lab/offsite-tuning).
